Feat/boz 7 contact opnemen
Pixel-Null/BureauOnbeperkteZaken pull request #32
Opened 2022-04-07 22:40 UTC by JentevdHoek

2022-04-08 10:12 UTC, JanSneeuw requested changes

2022-04-08 10:12 UTC, JanSneeuw commented on app/Http/Controllers/ContactController.php
> +    public function show(Message $message)
Misschien even de lege functies weghalen om nettere code te krijgen.

2022-04-08 10:12 UTC, JanSneeuw commented on resources/views/contact.blade.php
> +<body class="container">
Zorg dat je de door Roel gemaakte components gaat gebruiken zodat iedereen dezelfde layout heeft.

2022-04-08 10:12 UTC, JanSneeuw commented on routes/web.php
> +Route::post('index', [App\Http\Controllers\ContactController::class, 'store'])->name('store');
Geef deze functies een duidelijke unieke naam voor wat ze doen, dus in dit geval contact_store en contact_index.

2022-04-08 10:12 UTC, JanSneeuw commented on tests/Browser/ContactTest.php
> +<?php
Je mist tests, je dekt zo niet alle acceptatiecriteria. Je test alleen het happy path. Maak ook nog tests om te testen wat er gebeurt als het geen geldig email is of het bericht langer is dan 500 karakters. En een test om te checken of het bericht werkelijk op de website wordt opgeslagen.

2022-04-08 10:12 UTC, Pixel-Null requested changes

2022-04-08 10:12 UTC, Pixel-Null commented on resources/views/contact.blade.php
> +<?PHP
Gebruik page components

2022-04-09 23:07 UTC, JanSneeuw requested changes
paar laatste verbeter puntjes, verder ziet het er goed uit!

2022-04-10 14:16 UTC, JanSneeuw approved these changes

2022-04-10 14:21 UTC, RayNelemans approved these changes

2022-04-10 14:21 UTC, JanSneeuw approved these changes

2022-04-10 14:21 UTC, merged