Boz 90 als potentiele sponsor wil ik organisatorische informatie kunnen lezen zodat mijn vertrouwen in boz sterker wordt
Pixel-Null/BureauOnbeperkteZaken pull request #53
Opened 2022-05-30 18:04 UTC by RayNelemans

2022-05-30 19:48 UTC, JentevdHoek requested changes
Mag de composer.lock file wel mee naar development?
Anders alleen scaling ff beetje beter maken

2022-05-31 12:28 UTC, JentevdHoek requested changes
Alleen een nav item (of ergens ander ofzo) nodig om pagina te bereiken

2022-05-31 12:56 UTC, DevonAvans requested changes
Wat Jente zegt

2022-05-31 17:56 UTC, JanSneeuw requested changes
Graag tests voor het afvangen van je acceptatiecriteria

2022-05-31 20:15 UTC, JanSneeuw approved these changes

2022-05-31 20:15 UTC, DevonAvans submitted a review, later dismissed

2022-05-31 21:07 UTC, JanSneeuw approved these changes

2022-05-31 21:30 UTC, kjellgeerlings approved these changes
Comprehensive and pretty page. Well done

2022-05-31 21:32 UTC, merged