Feat/boz 65 over ons pagina
Pixel-Null/BureauOnbeperkteZaken pull request #59
Opened 2022-05-31 16:22 UTC by kjellgeerlings

Bad page. Reviews should be harsh <3

2022-05-31 17:36 UTC, DevonAvans commented on resources/views/overons.blade.php
> +        <label for="1" class="text-center" dusk="template"><img src="{{asset('img/Jojo_placeholder.jpg')}}"/></label>
alt attribuut 🏋️‍♀️

2022-05-31 17:38 UTC, DevonAvans commented
oh en inline styling in blokken weg zetten

2022-05-31 17:44 UTC, DevonAvans commented
Grid items schieten uit de grid zelf

2022-05-31 17:47 UTC, JanSneeuw requested changes
Zorg alsjeblieft dat de text op dezelfde hoogte zit in de grid. En zijn de foto's placeholders? Zo ja zorg dat dat duidelijk is zodat er geen verwarring ontstaat.

2022-05-31 21:00 UTC, DevonAvans commented on resources/views/overons.blade.php
>          <div class="paragraph" style="text-align: left;">
Dit bedoel ik

2022-05-31 21:01 UTC, DevonAvans commented on resources/views/overons.blade.php
>          <div class="paragraph" style="text-align: left;">
en paragraph class doet weinig is het nodig?

2022-06-06 17:39 UTC, DevonAvans commented on resources/views/overons.blade.php
>                              worden en niet ontkend.
Tekst zit in een div in plaats van een paragraaf, dit is wel belangrijk zeker voor de screenreaders

2022-06-06 18:01 UTC, JanSneeuw requested changes
De foto's zijn inmiddels binnen in de mail als het goed is. Die graag nog even toevoegen.

2022-06-06 18:01 UTC, JanSneeuw commented on routes/web.php
> +Route::get('/overons', function() {
Zou je dit via een controller willen doen in plaats van de view returnen in de route. Dit is misschien op het moment niet belangrijk, maar om de code uitbreidbaar te houden is het wel handig.

2022-06-07 11:12 UTC, DevonAvans approved these changes

2022-06-07 11:28 UTC, JanSneeuw approved these changes

2022-06-07 11:31 UTC, merged